# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_Main.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(1100, 649)
        Form.setMaximumSize(QtCore.QSize(1100, 649))
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 1080, 630))
        self.tabWidget.setIconSize(QtCore.QSize(20, 20))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(30, 0, 1011, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setGeometry(QtCore.QRect(30, 50, 1011, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.lb_video1 = QtWidgets.QLabel(self.tab)
        self.lb_video1.setGeometry(QtCore.QRect(30, 80, 790, 445))
        self.lb_video1.setMaximumSize(QtCore.QSize(1100, 650))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lb_video1.setFont(font)
        self.lb_video1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lb_video1.setAutoFillBackground(True)
        self.lb_video1.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_video1.setObjectName("lb_video1")
        self.bt_C1_PrintScreen = QtWidgets.QPushButton(self.tab)
        self.bt_C1_PrintScreen.setGeometry(QtCore.QRect(200, 550, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.bt_C1_PrintScreen.setFont(font)
        self.bt_C1_PrintScreen.setObjectName("bt_C1_PrintScreen")
        self.bt_C1_Enroll = QtWidgets.QPushButton(self.tab)
        self.bt_C1_Enroll.setGeometry(QtCore.QRect(360, 550, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.bt_C1_Enroll.setFont(font)
        self.bt_C1_Enroll.setObjectName("bt_C1_Enroll")
        self.line_2 = QtWidgets.QFrame(self.tab)
        self.line_2.setGeometry(QtCore.QRect(810, 80, 31, 445))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.bt_C1_Add = QtWidgets.QPushButton(self.tab)
        self.bt_C1_Add.setGeometry(QtCore.QRect(690, 550, 140, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.bt_C1_Add.setFont(font)
        self.bt_C1_Add.setObjectName("bt_C1_Add")
        self.lb_C1_Reminder = QtWidgets.QLabel(self.tab)
        self.lb_C1_Reminder.setGeometry(QtCore.QRect(20, 530, 790, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lb_C1_Reminder.setFont(font)
        self.lb_C1_Reminder.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_C1_Reminder.setObjectName("lb_C1_Reminder")
        self.bt_C1_Open = QtWidgets.QPushButton(self.tab)
        self.bt_C1_Open.setGeometry(QtCore.QRect(40, 550, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.bt_C1_Open.setFont(font)
        self.bt_C1_Open.setObjectName("bt_C1_Open")
        self.bt_C1_Close = QtWidgets.QPushButton(self.tab)
        self.bt_C1_Close.setGeometry(QtCore.QRect(530, 550, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.bt_C1_Close.setFont(font)
        self.bt_C1_Close.setObjectName("bt_C1_Close")
        self.list_C1_DBInfo = QtWidgets.QListWidget(self.tab)
        self.list_C1_DBInfo.setGeometry(QtCore.QRect(830, 80, 211, 445))
        self.list_C1_DBInfo.setObjectName("list_C1_DBInfo")
        self.lb_C1_DBTitle = QtWidgets.QLabel(self.tab)
        self.lb_C1_DBTitle.setGeometry(QtCore.QRect(830, 100, 211, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lb_C1_DBTitle.setFont(font)
        self.lb_C1_DBTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_C1_DBTitle.setObjectName("lb_C1_DBTitle")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(30, 0, 1011, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.line_3 = QtWidgets.QFrame(self.tab_2)
        self.line_3.setGeometry(QtCore.QRect(30, 50, 1011, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.lb_video2 = QtWidgets.QLabel(self.tab_2)
        self.lb_video2.setGeometry(QtCore.QRect(30, 80, 790, 445))
        self.lb_video2.setMaximumSize(QtCore.QSize(790, 445))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lb_video2.setFont(font)
        self.lb_video2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lb_video2.setAutoFillBackground(True)
        self.lb_video2.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_video2.setObjectName("lb_video2")
        self.bt_C2_Work = QtWidgets.QPushButton(self.tab_2)
        self.bt_C2_Work.setGeometry(QtCore.QRect(370, 550, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.bt_C2_Work.setFont(font)
        self.bt_C2_Work.setObjectName("bt_C2_Work")
        self.line_7 = QtWidgets.QFrame(self.tab_2)
        self.line_7.setGeometry(QtCore.QRect(810, 80, 31, 445))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.bt_C2_Close = QtWidgets.QPushButton(self.tab_2)
        self.bt_C2_Close.setGeometry(QtCore.QRect(580, 550, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.bt_C2_Close.setFont(font)
        self.bt_C2_Close.setObjectName("bt_C2_Close")
        self.bt_C2_Test = QtWidgets.QPushButton(self.tab_2)
        self.bt_C2_Test.setGeometry(QtCore.QRect(160, 550, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.bt_C2_Test.setFont(font)
        self.bt_C2_Test.setObjectName("bt_C2_Test")
        self.lb_C2_DBTitle = QtWidgets.QLabel(self.tab_2)
        self.lb_C2_DBTitle.setGeometry(QtCore.QRect(830, 100, 211, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lb_C2_DBTitle.setFont(font)
        self.lb_C2_DBTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_C2_DBTitle.setObjectName("lb_C2_DBTitle")
        self.list_C2_DBInfo = QtWidgets.QListWidget(self.tab_2)
        self.list_C2_DBInfo.setGeometry(QtCore.QRect(830, 80, 211, 445))
        self.list_C2_DBInfo.setObjectName("list_C2_DBInfo")
        self.label_4.raise_()
        self.line_3.raise_()
        self.lb_video2.raise_()
        self.bt_C2_Work.raise_()
        self.line_7.raise_()
        self.bt_C2_Close.raise_()
        self.bt_C2_Test.raise_()
        self.list_C2_DBInfo.raise_()
        self.lb_C2_DBTitle.raise_()
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_6 = QtWidgets.QLabel(self.tab_3)
        self.label_6.setGeometry(QtCore.QRect(30, 0, 1011, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.line_4 = QtWidgets.QFrame(self.tab_3)
        self.line_4.setGeometry(QtCore.QRect(30, 50, 1011, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.lb_video3 = QtWidgets.QLabel(self.tab_3)
        self.lb_video3.setGeometry(QtCore.QRect(30, 80, 790, 445))
        self.lb_video3.setMaximumSize(QtCore.QSize(790, 445))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lb_video3.setFont(font)
        self.lb_video3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lb_video3.setAutoFillBackground(True)
        self.lb_video3.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_video3.setObjectName("lb_video3")
        self.bt_C3_Open = QtWidgets.QPushButton(self.tab_3)
        self.bt_C3_Open.setGeometry(QtCore.QRect(920, 170, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.bt_C3_Open.setFont(font)
        self.bt_C3_Open.setObjectName("bt_C3_Open")
        self.line_6 = QtWidgets.QFrame(self.tab_3)
        self.line_6.setGeometry(QtCore.QRect(860, 80, 31, 441))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.bt_C3_Close = QtWidgets.QPushButton(self.tab_3)
        self.bt_C3_Close.setGeometry(QtCore.QRect(920, 280, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.bt_C3_Close.setFont(font)
        self.bt_C3_Close.setObjectName("bt_C3_Close")
        self.label_2 = QtWidgets.QLabel(self.tab_3)
        self.label_2.setGeometry(QtCore.QRect(40, 540, 711, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_8 = QtWidgets.QLabel(self.tab_4)
        self.label_8.setGeometry(QtCore.QRect(30, 0, 1011, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.line_5 = QtWidgets.QFrame(self.tab_4)
        self.line_5.setGeometry(QtCore.QRect(30, 50, 1011, 16))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_4)
        self.tabWidget_2.setGeometry(QtCore.QRect(30, 80, 1011, 511))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.groupBox = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox.setGeometry(QtCore.QRect(312, 20, 671, 451))
        self.groupBox.setObjectName("groupBox")
        self.list_C41_DBInfo = QtWidgets.QListWidget(self.groupBox)
        self.list_C41_DBInfo.setGeometry(QtCore.QRect(20, 30, 300, 401))
        self.list_C41_DBInfo.setObjectName("list_C41_DBInfo")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 20, 271, 221))
        self.groupBox_3.setObjectName("groupBox_3")
        self.bt_C41_searchDate = QtWidgets.QPushButton(self.groupBox_3)
        self.bt_C41_searchDate.setGeometry(QtCore.QRect(110, 180, 75, 23))
        self.bt_C41_searchDate.setObjectName("bt_C41_searchDate")
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(51, 51, 48, 16))
        self.label_11.setObjectName("label_11")
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setGeometry(QtCore.QRect(51, 151, 42, 16))
        self.label_13.setObjectName("label_13")
        self.input_C41_Num = QtWidgets.QLineEdit(self.groupBox_3)
        self.input_C41_Num.setGeometry(QtCore.QRect(105, 51, 133, 20))
        self.input_C41_Num.setObjectName("input_C41_Num")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(20, 30, 48, 12))
        self.label_10.setObjectName("label_10")
        self.bt_C41_searchNum = QtWidgets.QPushButton(self.groupBox_3)
        self.bt_C41_searchNum.setGeometry(QtCore.QRect(105, 77, 75, 23))
        self.bt_C41_searchNum.setObjectName("bt_C41_searchNum")
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setGeometry(QtCore.QRect(20, 130, 48, 12))
        self.label_12.setObjectName("label_12")
        self.input_C41_Date = QtWidgets.QDateEdit(self.groupBox_3)
        self.input_C41_Date.setGeometry(QtCore.QRect(110, 150, 131, 20))
        self.input_C41_Date.setObjectName("input_C41_Date")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 250, 271, 221))
        self.groupBox_4.setObjectName("groupBox_4")
        self.bt_C41_searchDate_Late = QtWidgets.QPushButton(self.groupBox_4)
        self.bt_C41_searchDate_Late.setGeometry(QtCore.QRect(110, 180, 75, 23))
        self.bt_C41_searchDate_Late.setObjectName("bt_C41_searchDate_Late")
        self.label_20 = QtWidgets.QLabel(self.groupBox_4)
        self.label_20.setGeometry(QtCore.QRect(20, 30, 48, 12))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.groupBox_4)
        self.label_21.setGeometry(QtCore.QRect(20, 130, 48, 12))
        self.label_21.setObjectName("label_21")
        self.input_C41_Num_Late = QtWidgets.QLineEdit(self.groupBox_4)
        self.input_C41_Num_Late.setGeometry(QtCore.QRect(110, 51, 133, 20))
        self.input_C41_Num_Late.setObjectName("input_C41_Num_Late")
        self.bt_C41_searchNum_Late = QtWidgets.QPushButton(self.groupBox_4)
        self.bt_C41_searchNum_Late.setGeometry(QtCore.QRect(110, 77, 75, 23))
        self.bt_C41_searchNum_Late.setObjectName("bt_C41_searchNum_Late")
        self.label_18 = QtWidgets.QLabel(self.groupBox_4)
        self.label_18.setGeometry(QtCore.QRect(51, 51, 48, 16))
        self.label_18.setObjectName("label_18")
        self.input_C41_Date_Late = QtWidgets.QDateEdit(self.groupBox_4)
        self.input_C41_Date_Late.setGeometry(QtCore.QRect(110, 150, 131, 20))
        self.input_C41_Date_Late.setObjectName("input_C41_Date_Late")
        self.label_19 = QtWidgets.QLabel(self.groupBox_4)
        self.label_19.setGeometry(QtCore.QRect(51, 151, 42, 16))
        self.label_19.setObjectName("label_19")
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_2.setGeometry(QtCore.QRect(312, 20, 671, 451))
        self.groupBox_2.setObjectName("groupBox_2")
        self.list_C42_DBInfo = QtWidgets.QListWidget(self.groupBox_2)
        self.list_C42_DBInfo.setEnabled(True)
        self.list_C42_DBInfo.setGeometry(QtCore.QRect(20, 30, 300, 401))
        self.list_C42_DBInfo.setObjectName("list_C42_DBInfo")
        self.widget = QtWidgets.QWidget(self.groupBox_2)
        self.widget.setGeometry(QtCore.QRect(330, 30, 321, 401))
        self.widget.setObjectName("widget")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_5.setGeometry(QtCore.QRect(20, 20, 271, 451))
        self.groupBox_5.setObjectName("groupBox_5")
        self.bt_C42_searchDate = QtWidgets.QPushButton(self.groupBox_5)
        self.bt_C42_searchDate.setGeometry(QtCore.QRect(110, 300, 75, 23))
        self.bt_C42_searchDate.setObjectName("bt_C42_searchDate")
        self.label_15 = QtWidgets.QLabel(self.groupBox_5)
        self.label_15.setGeometry(QtCore.QRect(51, 101, 48, 16))
        self.label_15.setObjectName("label_15")
        self.label_14 = QtWidgets.QLabel(self.groupBox_5)
        self.label_14.setGeometry(QtCore.QRect(20, 80, 48, 12))
        self.label_14.setObjectName("label_14")
        self.label_16 = QtWidgets.QLabel(self.groupBox_5)
        self.label_16.setGeometry(QtCore.QRect(51, 271, 42, 16))
        self.label_16.setObjectName("label_16")
        self.input_C42_Date = QtWidgets.QDateEdit(self.groupBox_5)
        self.input_C42_Date.setGeometry(QtCore.QRect(110, 270, 131, 20))
        self.input_C42_Date.setObjectName("input_C42_Date")
        self.input_C42_Num = QtWidgets.QLineEdit(self.groupBox_5)
        self.input_C42_Num.setGeometry(QtCore.QRect(105, 101, 133, 20))
        self.input_C42_Num.setObjectName("input_C42_Num")
        self.bt_C42_searchNum = QtWidgets.QPushButton(self.groupBox_5)
        self.bt_C42_searchNum.setGeometry(QtCore.QRect(105, 127, 75, 23))
        self.bt_C42_searchNum.setObjectName("bt_C42_searchNum")
        self.label_17 = QtWidgets.QLabel(self.groupBox_5)
        self.label_17.setGeometry(QtCore.QRect(20, 250, 48, 12))
        self.label_17.setObjectName("label_17")
        self.tabWidget_2.addTab(self.tab_6, "")
        self.tabWidget.addTab(self.tab_4, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "安全帽佩戴检测"))
        self.label.setText(_translate("Form", "上班签到"))
        self.lb_video1.setText(_translate("Form", "先开启摄像头"))
        self.bt_C1_PrintScreen.setText(_translate("Form", "拍照"))
        self.bt_C1_Enroll.setText(_translate("Form", "签到"))
        self.bt_C1_Add.setText(_translate("Form", "数据/模型更新"))
        self.lb_C1_Reminder.setText(_translate("Form", "签到结果提示"))
        self.bt_C1_Open.setText(_translate("Form", "开启"))
        self.bt_C1_Close.setText(_translate("Form", "关闭"))
        self.lb_C1_DBTitle.setText(_translate("Form", "今日签到信息"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "上班签到"))
        self.label_4.setText(_translate("Form", "摄像头实时检测"))
        self.lb_video2.setText(_translate("Form", "先开启摄像头"))
        self.bt_C2_Work.setText(_translate("Form", "工作模式"))
        self.bt_C2_Close.setText(_translate("Form", "关闭"))
        self.bt_C2_Test.setText(_translate("Form", "测试模式"))
        self.lb_C2_DBTitle.setText(_translate("Form", "今日未戴安全帽违规信息"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "摄像头实时检测"))
        self.label_6.setText(_translate("Form", "本地视频检测"))
        self.lb_video3.setText(_translate("Form", "请先打开要检测的本地视频"))
        self.bt_C3_Open.setText(_translate("Form", "打开"))
        self.bt_C3_Close.setText(_translate("Form", "关闭"))
        self.label_2.setText(_translate("Form", "注：“a”快退10秒、“d”快进10秒、“w”倍速增、“s”倍速减（最低1倍速,最高8倍速）"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "本地视频检测"))
        self.label_8.setText(_translate("Form", "图表统计"))
        self.groupBox.setTitle(_translate("Form", "查询结果"))
        self.groupBox_3.setTitle(_translate("Form", "签到信息查询"))
        self.bt_C41_searchDate.setText(_translate("Form", "查询"))
        self.label_11.setText(_translate("Form", "职工号："))
        self.label_13.setText(_translate("Form", "日  期："))
        self.label_10.setText(_translate("Form", "按职工："))
        self.bt_C41_searchNum.setText(_translate("Form", "查询"))
        self.label_12.setText(_translate("Form", "按日期："))
        self.groupBox_4.setTitle(_translate("Form", "迟到信息查询"))
        self.bt_C41_searchDate_Late.setText(_translate("Form", "查询"))
        self.label_20.setText(_translate("Form", "按职工："))
        self.label_21.setText(_translate("Form", "按日期："))
        self.bt_C41_searchNum_Late.setText(_translate("Form", "查询"))
        self.label_18.setText(_translate("Form", "职工号："))
        self.label_19.setText(_translate("Form", "日  期："))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("Form", "签到统计"))
        self.groupBox_2.setTitle(_translate("Form", "查询结果"))
        self.groupBox_5.setTitle(_translate("Form", "违规信息查询"))
        self.bt_C42_searchDate.setText(_translate("Form", "查询"))
        self.label_15.setText(_translate("Form", "职工号："))
        self.label_14.setText(_translate("Form", "按职工："))
        self.label_16.setText(_translate("Form", "日  期："))
        self.bt_C42_searchNum.setText(_translate("Form", "查询"))
        self.label_17.setText(_translate("Form", "按日期："))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("Form", "违规统计"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Form", "图表统计"))
